# Site settings
title: CoyIM
email: coyim@thoughtworks.com
description: > # this means to ignore newlines until "baseurl:"
    CoyIM is a new client for the XMPP protocol. It is built upon xmpp-client. It adds a graphical user interface and tries to be safe and secure by default. Our ambition is that it should be possible for even the most high-risk people on the planet to safely use CoyIM, without having to make any configuration changes.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://coy.im"

version: 0.1

# Build settings
markdown: kramdown
